### ISSUE TITLE
Database Replication

### ISSUE THREAD

**Issue by jhorne98** [YCPRadioTelescope/RT-Contracts#1]
This will be one of the other highest priority items for the Spring semester. As the application currently stands, all database communication occurs with the RDS instance. This will need to be modified to instead operate under the following principles:

- The control room should input radio frequency data to the MySQL database on the localhost that the software is running on.

- The localhost database will need to replicate information for the following tables: user, appointment, coordinate

- The RDS instance will need to replicate information for the following tables: appointment, rfdata

This is necessary in case internet connection at the control room is severed so that data integrity can be maintained

**Comment by Jlandau2** [comment]
Duplicate issue, resolved.
