### ISSUE TITLE
Prod API 500 error

### ISSUE THREAD

**Issue by Jlandau2** [YCPRadioTelescope/RT-Contracts#17]
User story: When a user (either developer or a project application) accesses the API an error is currently returned.

The front-end team has experienced an HTTP 505 error when trying to access sub-pages of the website. The error seems to be coming from the prod-api.

**Comment by jhorne98** [comment]
Temporarily suspended until issue can be replicated and tested in development environment. - jlandau

**Comment by Jlandau2** [comment]
Resolved, Prod API 500 no longer appears.
