### ISSUE TITLE
Standardize Endpoint Name Styles

### ISSUE THREAD

**Issue by jhorne98** [YCPRadioTelescope/RT-Contracts#30]
The HTTP endpoint names have varying styles. This leads to confusing design and can be confusing to those using the backend. Best practice would be renaming the endpoints in camelCase style. This also requires updating the SwaggerHub docs.

**Comment by lgartrell** [comment]
## Possible Plan
1. Find HTTP endpoints
2. Update naming conventions accordingly
3. Test endpoints to make sure they still work
4. Create list of updated endings and forward to teams impacted

## Teams Impacted
Front-End

**Comment by vmaresca** [comment]
I looked through the code and found no examples of this so I will be closing it without making any changes.
