### ISSUE TITLE
Sensor API calls need null checking

### ISSUE THREAD

**Issue by jhorne98** [YCPRadioTelescope/RT-Contracts#64]
Several of the sensor API calls do not have parameter checking and will accept null parameters on the controller layer without returning 400

**Comment by lgartrell** [comment]
## Possible Plan
1. find sensor API calls
2. investigate current parameter checking, verify do not have null checks
3. If need, add null checking to parameter calls
## Teams Impacted
backend

**Comment by vmaresca** [comment]
Issue was already completed.
