### ISSUE TITLE
Adding Firebase ID to User column for push notifications

### ISSUE THREAD

**Issue by lgartrell** [YCPRadioTelescope/RT-Contracts#75]

**Comment by lgartrell** [comment]
## Overview
To support push notifications, we need to add another type to the user.notification_type enum for PUSH_NOTIFICATION. In addition, we need an admin_firebase_id field to the user column --- could be seperate work, but for now will be grouped into this same issue.

## Possible plan of work
1. investigate user.notifcation_type enum
2. add PUSH_NOTIFICATION to the **end** of the enum list
3. investigate the user table
4. add admin_firebase_id field to the user column -- this should be defaulted to null
5. update user schema to represent new changes (schema is on the shared drive)
6. make sure the tests all still pass, and any schema representing the user table is updated

**Comment by tswann2ycp** [comment]
Added PUSHNOTIFICATION to the end of the enum, and added firebase_id to the user table. Having issue with the variable type with the enum list which needs to be fixed, then a couple things may need to be added to test. Updating schema now.
