### ISSUE TITLE
Modify User Update command to handle changing the user's notification type

### ISSUE THREAD

**Issue by jhorne98** [YCPRadioTelescope/RT-Contracts#8]
User story: A user with a notification type set to Text modifies their account information and gets rid of the phone number associated with their account

The problem: The user will now have a notification type that is invalid due to them no longer having a phone number associated with their account.

The solution: Given that a user with a notification type of Text modifies their account and removes their phone number, their notification type should be changed back to email

**Comment by lgartrell** [comment]
## Possible Work
1. Investigate update to user that changes their notification type
2. Investigate update that removes the user phone number
3. On removal of phone number, call update to notification type
4. Test changes

## Teams Impacted
backend

**Comment by pdnelson** [comment]
Looks like Joel already finished this one. Here's the commit: 03353b195d9cd4176a0cbbeb4c4f5e3666a9e684
