### ISSUE TITLE
Adding Latitude/Longitude/Altitude to the radio_telescope table

### ISSUE THREAD

**Issue by lgartrell** [YCPRadioTelescope/RT-Contracts#80]
## Work Needed
3 new columns requested to hold the Latitude, Longitude, and Altitude of the radio telescope. Getters and Setters need to accompany the new tables as well.

**Comment by pdnelson** [comment]
I looked into the RadioTelescope class in Control Room, and it looks like there's already a `location` field there, we just need to map it to the database. To avoid reworking a bunch of things, we'll actually have to add a `location` table and a `location_id` join column to the `radio_telescope` table.
